{% set name = "universal-analytics-python3" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/universal-analytics-python3-{{ version }}.tar.gz
  sha256: f58b6ab7cef2389aefed80f145b873e447dc4083256330f187122783792f7fad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pytest-runner
    - flake8
    - setuptools
    - pip
  run:
    - python >=3.7
    - httpx >=0.10.0

test:
  imports:
    - universal_analytics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmvass/universal-analytics-python3
  summary: Universal analytics python library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucasew
